language: node_js
node_js:
  - 12

os:
  - linux

cache:
  bundler: true
  directories:
    - node_modules

install:
  - npm install
  - make install

stages:
  - test
  - pack
  - name: deploy
    if: (type = push) AND branch =~ ^(master|v\d+\.\d+)$

script:
  - npm test

jobs:
  include:

    - stage: pack
      script:
        - make build

    - stage:
      script:
        - echo "Deploying ..."
      deploy:
        provider: surge
        project: ./docs/_site/
        domain: ai-ml.club
        skip_cleanup: true

notifications:
  email:
    on_success: change
    on_failure: change
